// <auto-generated />
using System;
using FormBuilder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormBuilder.Core.Migrations
{
    [DbContext(typeof(FormBuilderDbContext))]
    partial class FormBuilderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APPROVAL_DELEGATIONS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("APPROVAL_DELEGATIONS");
                });

            modelBuilder.Entity("FIELD_TYPES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AllowMultiple")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ForeignTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("HasOptions")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FIELD_TYPES");
                });

            modelBuilder.Entity("FORMULAS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpressionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ResultFieldId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormBuilderId");

                    b.HasIndex("ResultFieldId");

                    b.ToTable("FORMULAS");
                });

            modelBuilder.Entity("FORM_FIELDS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FieldOrder")
                        .HasColumnType("int");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ForeignFieldName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ForeignHintText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForeignPlaceholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForeignValidationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GridId")
                        .HasColumnType("int");

                    b.Property<string>("HintText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegexPattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TabId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FieldTypeId");

                    b.HasIndex("GridId");

                    b.HasIndex("TabId");

                    b.ToTable("FORM_FIELDS");
                });

            modelBuilder.Entity("FORM_GRIDS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int");

                    b.Property<string>("GridCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GridName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GridOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("TabId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormBuilderId");

                    b.HasIndex("TabId");

                    b.ToTable("FORM_GRIDS");
                });

            modelBuilder.Entity("FORM_SUBMISSIONS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubmittedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("FormBuilderId");

                    b.HasIndex("SeriesId");

                    b.ToTable("FORM_SUBMISSIONS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.ALERT_RULES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmailTemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetRoleId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("ALERT_RULES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.APPROVAL_STAGES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalStage")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StageOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("APPROVAL_STAGES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.APPROVAL_STAGE_ASSIGNEES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("APPROVAL_STAGE_ASSIGNEES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.DOCUMENT_APPROVAL_HISTORY", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("DOCUMENT_APPROVAL_HISTORY");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.EMAIL_TEMPLATES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyTemplateHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("SmtpConfigId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("SmtpConfigId");

                    b.ToTable("EMAIL_TEMPLATES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForeignDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForeignFormName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormCode")
                        .IsUnique();

                    b.ToTable("FORM_BUILDER");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_GRID_COLUMNS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ColumnOrder")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GridId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationRuleJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FieldTypeId");

                    b.HasIndex("GridId");

                    b.ToTable("FORM_GRID_COLUMNS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_SUBMISSION_GRID_CELLS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColumnId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ValueString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.HasIndex("RowId");

                    b.ToTable("FORM_SUBMISSION_GRID_CELLS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_SUBMISSION_GRID_ROWS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GridId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GridId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("FORM_SUBMISSION_GRID_ROWS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_TABS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ForeignTabName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TabCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TabName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TabOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormBuilderId");

                    b.ToTable("FORM_TABS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.ADOBE_SIGNATURE_CONFIG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("ADOBE_SIGNATURE_CONFIG");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.APPROVAL_WORKFLOWS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("APPROVAL_WORKFLOWS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.ATTACHMENT_TYPES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxSizeMB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ATTACHMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.CRYSTAL_LAYOUTS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LayoutPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("CRYSTAL_LAYOUTS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_SERIES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("NextNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SeriesCode")
                        .IsUnique();

                    b.ToTable("DOCUMENT_SERIES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Code");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int")
                        .HasColumnName("FormBuilderId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("MenuCaption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MenuCaption");

                    b.Property<int>("MenuOrder")
                        .HasColumnType("int")
                        .HasColumnName("MenuOrder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("int")
                        .HasColumnName("ParentMenuId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FormBuilderId");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("DOCUMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.FORM_ATTACHMENT_TYPES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttachmentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentTypeId");

                    b.HasIndex("FormBuilderId");

                    b.ToTable("FORM_ATTACHMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.FORM_BUTTONS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ButtonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ButtonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ButtonOrder")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisibleDefault")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormBuilderId");

                    b.ToTable("FORM_BUTTONS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.FORM_SUBMISSION_ATTACHMENTS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("FORM_SUBMISSION_ATTACHMENTS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.FORM_VALIDATION_RULES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExpressionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("FormBuilderId");

                    b.ToTable("FORM_VALIDATION_RULES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.OUTLOOK_APPROVAL_CONFIG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mailbox")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("OUTLOOK_APPROVAL_CONFIG");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.PROJECTS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PROJECTS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.SAP_FIELD_MAPPINGS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("FormFieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SapFieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormFieldId");

                    b.ToTable("SAP_FIELD_MAPPINGS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.SAP_OBJECT_MAPPINGS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDraftOnly")
                        .HasColumnType("bit");

                    b.Property<string>("SapObjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("SAP_OBJECT_MAPPINGS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.SMTP_CONFIGS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SMTP_CONFIGS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FIELD_DATA_SOURCES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiPath")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RequestBodyJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TextPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValuePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("FIELD_DATA_SOURCES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FIELD_OPTIONS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("ForeignOptionText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("FIELD_OPTIONS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORMULA_VARIABLES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormulaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SourceFieldId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VariableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FormulaId");

                    b.HasIndex("SourceFieldId");

                    b.ToTable("FORMULA_VARIABLES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORM_RULES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionField")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConditionOperator")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConditionValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConditionValueType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExecutionOrder")
                        .HasColumnType("int");

                    b.Property<int>("FormBuilderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RuleJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FormBuilderId");

                    b.ToTable("FORM_RULES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORM_RULE_ACTIONS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionOrder")
                        .HasColumnType("int");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Expression")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FieldCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsElseAction")
                        .HasColumnType("bit");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("FORM_RULE_ACTIONS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORM_SUBMISSION_VALUES", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValueNumber")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ValueString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("FORM_SUBMISSION_VALUES");
                });

            modelBuilder.Entity("formBuilder.Domian.Entitys.REFRESH_TOKENS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("REFRESH_TOKENS");
                });

            modelBuilder.Entity("FORMULAS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany("FORMULAS")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FORM_FIELDS", "RESULT_FIELD")
                        .WithMany()
                        .HasForeignKey("ResultFieldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FORM_BUILDER");

                    b.Navigation("RESULT_FIELD");
                });

            modelBuilder.Entity("FORM_FIELDS", b =>
                {
                    b.HasOne("FIELD_TYPES", "FIELD_TYPES")
                        .WithMany("FORM_FIELDS")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FORM_GRIDS", "Grid")
                        .WithMany()
                        .HasForeignKey("GridId");

                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_TABS", "FORM_TABS")
                        .WithMany("FORM_FIELDS")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FIELD_TYPES");

                    b.Navigation("FORM_TABS");

                    b.Navigation("Grid");
                });

            modelBuilder.Entity("FORM_GRIDS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany("FORM_GRIDS")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_TABS", "FORM_TABS")
                        .WithMany("FORM_GRIDS")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FORM_BUILDER");

                    b.Navigation("FORM_TABS");
                });

            modelBuilder.Entity("FORM_SUBMISSIONS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("FORM_SUBMISSIONS")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany("FORM_SUBMISSIONS")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_SERIES", "DOCUMENT_SERIES")
                        .WithMany("FORM_SUBMISSIONS")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DOCUMENT_SERIES");

                    b.Navigation("DOCUMENT_TYPES");

                    b.Navigation("FORM_BUILDER");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.ALERT_RULES", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("ALERT_RULES")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.EMAIL_TEMPLATES", "EMAIL_TEMPLATES")
                        .WithMany("ALERT_RULES")
                        .HasForeignKey("EmailTemplateId");

                    b.Navigation("DOCUMENT_TYPES");

                    b.Navigation("EMAIL_TEMPLATES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.APPROVAL_STAGES", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.APPROVAL_WORKFLOWS", "APPROVAL_WORKFLOWS")
                        .WithMany("APPROVAL_STAGES")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APPROVAL_WORKFLOWS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.APPROVAL_STAGE_ASSIGNEES", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.APPROVAL_STAGES", "APPROVAL_STAGES")
                        .WithMany("APPROVAL_STAGE_ASSIGNEES")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("APPROVAL_STAGES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.DOCUMENT_APPROVAL_HISTORY", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.APPROVAL_STAGES", "APPROVAL_STAGES")
                        .WithMany("DOCUMENT_APPROVAL_HISTORY")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FORM_SUBMISSIONS", "FORM_SUBMISSIONS")
                        .WithMany("DOCUMENT_APPROVAL_HISTORY")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("APPROVAL_STAGES");

                    b.Navigation("FORM_SUBMISSIONS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.EMAIL_TEMPLATES", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("EMAIL_TEMPLATES")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.SMTP_CONFIGS", "SMTP_CONFIGS")
                        .WithMany("EMAIL_TEMPLATES")
                        .HasForeignKey("SmtpConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DOCUMENT_TYPES");

                    b.Navigation("SMTP_CONFIGS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_GRID_COLUMNS", b =>
                {
                    b.HasOne("FIELD_TYPES", "FIELD_TYPES")
                        .WithMany("FORM_GRID_COLUMNS")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FORM_GRIDS", "FORM_GRIDS")
                        .WithMany("FORM_GRID_COLUMNS")
                        .HasForeignKey("GridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FIELD_TYPES");

                    b.Navigation("FORM_GRIDS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_SUBMISSION_GRID_CELLS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_GRID_COLUMNS", "FORM_GRID_COLUMNS")
                        .WithMany("FORM_SUBMISSION_GRID_CELLS")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_SUBMISSION_GRID_ROWS", "FORM_SUBMISSION_GRID_ROWS")
                        .WithMany("FORM_SUBMISSION_GRID_CELLS")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_GRID_COLUMNS");

                    b.Navigation("FORM_SUBMISSION_GRID_ROWS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_SUBMISSION_GRID_ROWS", b =>
                {
                    b.HasOne("FORM_GRIDS", "FORM_GRIDS")
                        .WithMany("FORM_SUBMISSION_GRID_ROWS")
                        .HasForeignKey("GridId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FORM_SUBMISSIONS", "FORM_SUBMISSIONS")
                        .WithMany("FORM_SUBMISSION_GRID_ROWS")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_GRIDS");

                    b.Navigation("FORM_SUBMISSIONS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_TABS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany("FORM_TABS")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_BUILDER");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.ADOBE_SIGNATURE_CONFIG", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("ADOBE_SIGNATURE_CONFIG")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DOCUMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.APPROVAL_WORKFLOWS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("APPROVAL_WORKFLOWS")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DOCUMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.CRYSTAL_LAYOUTS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("CRYSTAL_LAYOUTS")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DOCUMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_SERIES", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("DOCUMENT_SERIES")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.PROJECTS", "PROJECTS")
                        .WithMany("DOCUMENT_SERIES")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DOCUMENT_TYPES");

                    b.Navigation("PROJECTS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany()
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "ParentMenu")
                        .WithMany("Children")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FORM_BUILDER");

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.FORM_ATTACHMENT_TYPES", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.ATTACHMENT_TYPES", "ATTACHMENT_TYPES")
                        .WithMany("FORM_ATTACHMENT_TYPES")
                        .HasForeignKey("AttachmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany("FORM_ATTACHMENT_TYPES")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ATTACHMENT_TYPES");

                    b.Navigation("FORM_BUILDER");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.FORM_BUTTONS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany("FORM_BUTTONS")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_BUILDER");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.FORM_SUBMISSION_ATTACHMENTS", b =>
                {
                    b.HasOne("FORM_FIELDS", "FORM_FIELDS")
                        .WithMany("FORM_SUBMISSION_ATTACHMENTS")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FORM_SUBMISSIONS", "FORM_SUBMISSIONS")
                        .WithMany("FORM_SUBMISSION_ATTACHMENTS")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FORM_FIELDS");

                    b.Navigation("FORM_SUBMISSIONS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.FORM_VALIDATION_RULES", b =>
                {
                    b.HasOne("FORM_FIELDS", "FORM_FIELDS")
                        .WithMany()
                        .HasForeignKey("FieldId");

                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany("FORM_VALIDATION_RULES")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_BUILDER");

                    b.Navigation("FORM_FIELDS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.OUTLOOK_APPROVAL_CONFIG", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("OUTLOOK_APPROVAL_CONFIG")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DOCUMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.SAP_FIELD_MAPPINGS", b =>
                {
                    b.HasOne("FORM_FIELDS", "FORM_FIELDS")
                        .WithMany("SAP_FIELD_MAPPINGS")
                        .HasForeignKey("FormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_FIELDS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.SAP_OBJECT_MAPPINGS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", "DOCUMENT_TYPES")
                        .WithMany("SAP_OBJECT_MAPPINGS")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DOCUMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FIELD_DATA_SOURCES", b =>
                {
                    b.HasOne("FORM_FIELDS", "FORM_FIELDS")
                        .WithMany("FIELD_DATA_SOURCES")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_FIELDS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FIELD_OPTIONS", b =>
                {
                    b.HasOne("FORM_FIELDS", "FORM_FIELDS")
                        .WithMany("FIELD_OPTIONS")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_FIELDS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORMULA_VARIABLES", b =>
                {
                    b.HasOne("FORMULAS", "FORMULAS")
                        .WithMany("FORMULA_VARIABLES")
                        .HasForeignKey("FormulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FORM_FIELDS", "FORM_FIELDS")
                        .WithMany("FORMULA_VARIABLES")
                        .HasForeignKey("SourceFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FORMULAS");

                    b.Navigation("FORM_FIELDS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORM_RULES", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", "FORM_BUILDER")
                        .WithMany("FORM_RULES")
                        .HasForeignKey("FormBuilderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_BUILDER");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORM_RULE_ACTIONS", b =>
                {
                    b.HasOne("FormBuilder.Domian.Entitys.froms.FORM_RULES", "FORM_RULES")
                        .WithMany("FORM_RULE_ACTIONS")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FORM_RULES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORM_SUBMISSION_VALUES", b =>
                {
                    b.HasOne("FORM_FIELDS", "FORM_FIELDS")
                        .WithMany("FORM_SUBMISSION_VALUES")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FORM_SUBMISSIONS", "FORM_SUBMISSIONS")
                        .WithMany("FORM_SUBMISSION_VALUES")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FORM_FIELDS");

                    b.Navigation("FORM_SUBMISSIONS");
                });

            modelBuilder.Entity("FIELD_TYPES", b =>
                {
                    b.Navigation("FORM_FIELDS");

                    b.Navigation("FORM_GRID_COLUMNS");
                });

            modelBuilder.Entity("FORMULAS", b =>
                {
                    b.Navigation("FORMULA_VARIABLES");
                });

            modelBuilder.Entity("FORM_FIELDS", b =>
                {
                    b.Navigation("FIELD_DATA_SOURCES");

                    b.Navigation("FIELD_OPTIONS");

                    b.Navigation("FORMULA_VARIABLES");

                    b.Navigation("FORM_SUBMISSION_ATTACHMENTS");

                    b.Navigation("FORM_SUBMISSION_VALUES");

                    b.Navigation("SAP_FIELD_MAPPINGS");
                });

            modelBuilder.Entity("FORM_GRIDS", b =>
                {
                    b.Navigation("FORM_GRID_COLUMNS");

                    b.Navigation("FORM_SUBMISSION_GRID_ROWS");
                });

            modelBuilder.Entity("FORM_SUBMISSIONS", b =>
                {
                    b.Navigation("DOCUMENT_APPROVAL_HISTORY");

                    b.Navigation("FORM_SUBMISSION_ATTACHMENTS");

                    b.Navigation("FORM_SUBMISSION_GRID_ROWS");

                    b.Navigation("FORM_SUBMISSION_VALUES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.APPROVAL_STAGES", b =>
                {
                    b.Navigation("APPROVAL_STAGE_ASSIGNEES");

                    b.Navigation("DOCUMENT_APPROVAL_HISTORY");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.EMAIL_TEMPLATES", b =>
                {
                    b.Navigation("ALERT_RULES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_BUILDER", b =>
                {
                    b.Navigation("FORMULAS");

                    b.Navigation("FORM_ATTACHMENT_TYPES");

                    b.Navigation("FORM_BUTTONS");

                    b.Navigation("FORM_GRIDS");

                    b.Navigation("FORM_RULES");

                    b.Navigation("FORM_SUBMISSIONS");

                    b.Navigation("FORM_TABS");

                    b.Navigation("FORM_VALIDATION_RULES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_GRID_COLUMNS", b =>
                {
                    b.Navigation("FORM_SUBMISSION_GRID_CELLS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_SUBMISSION_GRID_ROWS", b =>
                {
                    b.Navigation("FORM_SUBMISSION_GRID_CELLS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FormBuilder.FORM_TABS", b =>
                {
                    b.Navigation("FORM_FIELDS");

                    b.Navigation("FORM_GRIDS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.APPROVAL_WORKFLOWS", b =>
                {
                    b.Navigation("APPROVAL_STAGES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.ATTACHMENT_TYPES", b =>
                {
                    b.Navigation("FORM_ATTACHMENT_TYPES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_SERIES", b =>
                {
                    b.Navigation("FORM_SUBMISSIONS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.DOCUMENT_TYPES", b =>
                {
                    b.Navigation("ADOBE_SIGNATURE_CONFIG");

                    b.Navigation("ALERT_RULES");

                    b.Navigation("APPROVAL_WORKFLOWS");

                    b.Navigation("CRYSTAL_LAYOUTS");

                    b.Navigation("Children");

                    b.Navigation("DOCUMENT_SERIES");

                    b.Navigation("EMAIL_TEMPLATES");

                    b.Navigation("FORM_SUBMISSIONS");

                    b.Navigation("OUTLOOK_APPROVAL_CONFIG");

                    b.Navigation("SAP_OBJECT_MAPPINGS");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.PROJECTS", b =>
                {
                    b.Navigation("DOCUMENT_SERIES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.FromBuilder.SMTP_CONFIGS", b =>
                {
                    b.Navigation("EMAIL_TEMPLATES");
                });

            modelBuilder.Entity("FormBuilder.Domian.Entitys.froms.FORM_RULES", b =>
                {
                    b.Navigation("FORM_RULE_ACTIONS");
                });
#pragma warning restore 612, 618
        }
    }
}
