// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormBuilder.core.migrationdb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118095447_InitAppDatabase2")]
    partial class InitAppDatabase2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilder.API.Models.FORM_TABS", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("FormBuilderID")
                        .HasColumnType("int")
                        .HasColumnName("FormBuilderID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("TabName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TabName");

                    b.Property<int>("TabOrder")
                        .HasColumnType("int")
                        .HasColumnName("TabOrder");

                    b.HasKey("id");

                    b.HasIndex("FormBuilderID", "TabOrder")
                        .IsUnique();

                    b.ToTable("FORM_TABS");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilder.API.Models.FieldType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DataType");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int")
                        .HasColumnName("MaxLength");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TypeName");

                    b.HasKey("id");

                    b.ToTable("FIELD_TYPES");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilder.API.Models.FormField", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DataType");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DefaultValue");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FieldName");

                    b.Property<int>("FieldOrder")
                        .HasColumnType("int")
                        .HasColumnName("FieldOrder");

                    b.Property<int>("FieldTypeID")
                        .HasColumnType("int")
                        .HasColumnName("FieldTypeID");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit")
                        .HasColumnName("IsEditable");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit")
                        .HasColumnName("IsMandatory");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int")
                        .HasColumnName("MaxLength");

                    b.Property<int>("TabID")
                        .HasColumnType("int")
                        .HasColumnName("TabID");

                    b.Property<string>("ValidationRules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValidationRules");

                    b.HasKey("id");

                    b.HasIndex("FieldTypeID");

                    b.HasIndex("TabID", "FieldOrder")
                        .IsUnique();

                    b.ToTable("FORM_FIELDS");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilders", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("FormCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FormCode");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("FormName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.HasKey("id");

                    b.HasIndex("FormCode")
                        .IsUnique();

                    b.ToTable("FORM_BUILDERS");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilder.API.Models.FORM_TABS", b =>
                {
                    b.HasOne("FormBuilder.API.Models.FormBuilders", "FormBuilder")
                        .WithMany("FormTabs")
                        .HasForeignKey("FormBuilderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormBuilder");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilder.API.Models.FormField", b =>
                {
                    b.HasOne("FormBuilder.API.Models.FormBuilder.API.Models.FieldType", "FieldType")
                        .WithMany("FormFields")
                        .HasForeignKey("FieldTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormBuilder.API.Models.FormBuilder.API.Models.FORM_TABS", "FormTab")
                        .WithMany("FormFields")
                        .HasForeignKey("TabID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldType");

                    b.Navigation("FormTab");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilder.API.Models.FORM_TABS", b =>
                {
                    b.Navigation("FormFields");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilder.API.Models.FieldType", b =>
                {
                    b.Navigation("FormFields");
                });

            modelBuilder.Entity("FormBuilder.API.Models.FormBuilders", b =>
                {
                    b.Navigation("FormTabs");
                });
#pragma warning restore 612, 618
        }
    }
}
